version: '3.8'

services:
  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: satco-gotenberg
    ports:
      - "3000:3000"
    environment:
      - API_TIMEOUT=30s
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s